- name: Search for services - {{ search_services_ldap_filter }}
  isim:
    hostname: "{{ inventory_hostname }}"
    app_port:  "{{ app_port }}"
    root_dn:   "{{ root_dn }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: isimws.isim.service.search
    isimapi:
      container_dn:                   "{{ search_services_container_dn }}"
      ldap_filter:                    "{{ search_services_ldap_filter }}"
  when:
    - search_services_container_dn is defined
