- name: Create or modify an identity feed - {{ apply_identity_feed_name }}
  isim:
    hostname: "{{ inventory_hostname }}"
    app_port:  "{{ app_port }}"
    root_dn:   "{{ root_dn }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: isimws.isim.service.apply_identity_feed
    isimapi:
      container_path:                 "{{ apply_identity_feed_container_path }}"
      name:                           "{{ apply_identity_feed_name }}"
      service_type:                   "{{ apply_identity_feed_service_type }}"
      description:                    "{{ apply_identity_feed_description }}"
      use_workflow:                   "{{ apply_identity_feed_use_workflow }}"
      evaluate_sod:                   "{{ apply_identity_feed_evaluate_sod }}"
      placement_rule:                 "{{ apply_identity_feed_placement_rule }}"
      configuration:                  "{{ apply_identity_feed_configuration }}"
  when:
    - apply_identity_feed_container_path is defined
    - apply_identity_feed_name is defined
    - apply_identity_feed_service_type is defined
