- name: Create or modify a role - {{ apply_role_name }}
  isim:
    hostname: "{{ inventory_hostname }}"
    app_port:  "{{ app_port }}"
    root_dn:   "{{ root_dn }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: isimws.isim.role.apply
    isimapi:
      container_path:                 "{{ apply_role_container_path }}"
      name:                           "{{ apply_role_name }}"
      role_classification:            "{{ apply_role_role_classification }}"
      description:                    "{{ apply_role_description }}"
      role_owners:                    "{{ apply_role_role_owners }}"
      user_owners:                    "{{ apply_role_user_owners }}"
      enable_access:                  "{{ apply_role_enable_access }}"
      common_access:                  "{{ apply_role_common_access }}"
      access_type:                    "{{ apply_role_access_type }}"
      access_image_uri:               "{{ apply_role_access_image_uri }}"
      access_search_terms:            "{{ apply_role_access_search_terms }}"
      access_additional_info:         "{{ apply_role_access_additional_info }}"
      access_badges:                  "{{ apply_role_access_badges }}"
      assignment_attributes:          "{{ apply_role_assignment_attributes }}"
  when:
    - apply_role_container_path is defined
    - apply_role_name is defined
    - apply_role_role_classification is defined
