---
- hosts: all
  connection: local
  roles:
     - role: search_containers
       search_containers_parent_dn: 'erglobalid=00000000000000000000,ou=demo,dc=com'
       search_containers_container_name: 'testou'
       search_containers_profile: 'OrganizationalUnit'
       
     - role: apply_container
       apply_container_parent_container_path: '//demo//lo::Sydney'
       apply_container_profile: 'OrganizationalUnit'
       apply_container_name: 'ou1'
       apply_container_description: 'A description'
       apply_container_associated_people:
            - ['//demo//lo::Sydney//ou::ou1//bp::testing', 'cspeed']
            - ['//demo//lo::Sydney//ou::ou1', 'bjones']
            - ['//IBM', 'ayang']
