---
- hosts: all
  connection: local
  roles:
    - role: search_people
      search_people_ldap_filter: '(uid=*)'
  
    - role: apply_person
      apply_person_container_path: '//demo//lo::Sydney//ou::ou1//bp::testing'
      apply_person_uid: 'jbloggs'
      apply_person_profile: 'Person'
      apply_person_full_name: 'Joe Bloggs'
      apply_person_surname: 'Bloggs'
      apply_person_aliases:
        - 'JB'
        - 'Joe'
      apply_person_password: 'Passw0rd'
      apply_person_roles:
        - ["//demo", "new-role"]
        - ["//demo", "Demo Role"]
            