- name: Search for people - {{ search_people_ldap_filter }}
  isim:
    hostname: "{{ inventory_hostname }}"
    app_port:  "{{ app_port }}"
    root_dn:   "{{ root_dn }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: isimws.isim.person.search
    isimapi:
      ldap_filter:                    "{{ search_people_ldap_filter }}"

