- name: Create or modify a container - {{ apply_container_name }}
  isim:
    hostname: "{{ inventory_hostname }}"
    app_port:  "{{ app_port }}"
    root_dn:   "{{ root_dn }}"
    username:  "{{ username }}"
    password:  "{{ password }}"
    log:       "{{ log_level }}"
    force:     "{{ force }}"
    action: isimws.isim.container.apply
    isimapi:
      parent_container_path:                 "{{ apply_container_parent_container_path }}"
      profile:                               "{{ apply_container_profile }}"
      name:                                  "{{ apply_container_name }}"
      description:                           "{{ apply_container_description }}"
      associated_people:                     "{{ apply_container_associated_people }}"
  when:
    - apply_container_parent_container_path is defined
    - apply_container_profile is defined
    - apply_container_name is defined
