galaxy_info:
  author: IBM
  description: Role to retrieve information about a role using it's DN.
  company: IBM

  license: Apache

  min_ansible_version: 2.2
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isim
  - ibm
  - role
  - get

dependencies:
  - start_config
